// Command Intercom-cli is a CLI + REPL for the Intercom SDK,
// built on the boru engine. Positional arguments are joined into a
// single boru expression and evaluated; with no arguments, falls into
// a REPL. Generated by sdkgen go-cli target.
package main

import (
	"bufio"
	"fmt"
	"io"
	"os"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	"github.com/boru-lang/boru/eng/go/parser"
	sdk "github.com/voxgig-sdk/intercom-sdk/go"
)

// prompt is the REPL prompt prefix (matches the SDK slug).
const prompt = "intercom"

// entitiesHelp is the space-separated entity list shown by /help.
const entitiesHelp = "activity_log activity_log_event_type activity_log_list admin admin_with_app ai_call ai_content article article_search article_version article_version_list audience away_status_reason banner banner_dismiss brand call company company_attached_contact company_attached_segment company_list company_scroll contact contact_attached_company contact_list contact_segment content content_import_source content_search content_snippet conversation conversation_attribute conversation_attribute_list conversation_list conversation_participant custom_object_instance data data_attribute data_connector data_connector_execution_result data_connector_execution_result_list data_event data_event_summary data_export deleted deleted_article_object deleted_company_object deleted_data_connector_object deleted_internal_article_object deleted_object email external_page fin_agent handling_event help_center internal_article internal_article_search ip_allowlist job macro merge_history message news_item newsfeed note office_hour office_hours_exception office_hours_schedule paginated phone_switch reporting_data reporting_data_export segment side_conversation subscription subscription_type tag team team_metric_list ticket ticket_list ticket_reply ticket_state ticket_type ticket_type_attribute visitor whatsapp_message_status whatsapp_message_status_list workflow"

func main() {
	os.Exit(run(os.Args[1:], os.Stdin, os.Stdout, os.Stderr))
}

// usage prints the CLI help (for --help / -h). No client or network setup.
func usage(out io.Writer) {
	fmt.Fprintf(out, "%s-cli — boru-driven CLI + REPL for the %s SDK\n\n", prompt, prompt)
	fmt.Fprintln(out, "Usage:")
	fmt.Fprintf(out, "  %s-cli [--help] [<boru expression>]\n\n", prompt)
	fmt.Fprintln(out, "With arguments, they are joined into a single boru expression and")
	fmt.Fprintln(out, "evaluated against the API. With no arguments, starts an interactive REPL.")
	fmt.Fprintln(out)
	fmt.Fprintln(out, "Words:    list / load / update <query?> <entity>")
	fmt.Fprintln(out, "Entities:", entitiesHelp)
	fmt.Fprintln(out, "Env:      INTERCOM_APIKEY (api key), INTERCOM_BASE (base url override)")
	fmt.Fprintln(out, "REPL:     /help  /quit")
}

func run(args []string, in io.Reader, out, errOut io.Writer) int {
	// --help / -h: print usage and exit before any config or network setup.
	for _, a := range args {
		if a == "--help" || a == "-h" {
			usage(out)
			return 0
		}
	}

	// Configure from the environment: INTERCOM_APIKEY carries the API key and
	// INTERCOM_BASE optionally overrides the API base URL (e.g. production).
	// Both injectable by a secrets vault. Unset -> nil config defaults.
	var opts map[string]any
	if apikey := os.Getenv("INTERCOM_APIKEY"); apikey != "" {
		opts = map[string]any{"apikey": apikey}
	}
	if base := os.Getenv("INTERCOM_BASE"); base != "" {
		if opts == nil {
			opts = map[string]any{}
		}
		opts["base"] = base
	}
	client := sdk.NewIntercomSDK(opts)

	r, err := eng.NewRegistry()
	if err != nil {
		fmt.Fprintf(errOut, "registry: %v\n", err)
		return 1
	}
	registerSDKWords(r, client)
	if err := r.Err(); err != nil {
		fmt.Fprintf(errOut, "word registration: %v\n", err)
		return 1
	}
	r.SetParseFunc(parser.Parse)
	r.InitRootContext()
	r.MarkReady()

	if len(args) > 0 {
		return evalOnce(r, strings.Join(args, " "), out, errOut)
	}
	repl(r, in, out)
	return 0
}

func evalOnce(r *eng.Registry, src string, out, errOut io.Writer) int {
	values, err := parser.Parse(src)
	if err != nil {
		fmt.Fprintf(errOut, "parse: %v\n", err)
		return 1
	}
	result, err := eng.NewTop(r).Run(values)
	if err != nil {
		fmt.Fprintf(errOut, "error: %v\n", err)
		return 1
	}
	for _, v := range result {
		fmt.Fprintln(out, v.String())
	}
	return 0
}

func repl(r *eng.Registry, in io.Reader, out io.Writer) {
	scanner := bufio.NewScanner(in)
	scanner.Buffer(make([]byte, 0, 64*1024), 1024*1024)
	for {
		fmt.Fprintf(out, "%s> ", prompt)
		if !scanner.Scan() {
			fmt.Fprintln(out)
			return
		}
		line := strings.TrimSpace(scanner.Text())
		if line == "" {
			continue
		}
		switch line {
		case "/quit", "/q", "/exit":
			return
		case "/help", "/h", "/?":
			fmt.Fprintln(out, "words:    list / load / update <query?> <entity>")
			fmt.Fprintln(out, "entities:", entitiesHelp)
			fmt.Fprintln(out, "meta:     /help  /quit")
			continue
		}
		values, err := parser.Parse(line)
		if err != nil {
			fmt.Fprintf(out, "  parse error: %v\n", err)
			continue
		}
		result, err := eng.NewTop(r).Run(values)
		if err != nil {
			fmt.Fprintf(out, "  error: %v\n", err)
			continue
		}
		for _, v := range result {
			fmt.Fprintln(out, v.String())
		}
	}
}
