// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/intercom-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.IntercomSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.IntercomSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.IntercomSDK, name string) (sdk.IntercomEntity, error) {
	switch strings.ToLower(name) {
	case "activity_log":
		return client.ActivityLog(nil), nil
	case "activity_log_event_type":
		return client.ActivityLogEventType(nil), nil
	case "activity_log_list":
		return client.ActivityLogList(nil), nil
	case "admin":
		return client.Admin(nil), nil
	case "admin_with_app":
		return client.AdminWithApp(nil), nil
	case "ai_call":
		return client.AiCall(nil), nil
	case "ai_content":
		return client.AiContent(nil), nil
	case "article":
		return client.Article(nil), nil
	case "article_search":
		return client.ArticleSearch(nil), nil
	case "article_version":
		return client.ArticleVersion(nil), nil
	case "article_version_list":
		return client.ArticleVersionList(nil), nil
	case "audience":
		return client.Audience(nil), nil
	case "away_status_reason":
		return client.AwayStatusReason(nil), nil
	case "banner":
		return client.Banner(nil), nil
	case "banner_dismiss":
		return client.BannerDismiss(nil), nil
	case "brand":
		return client.Brand(nil), nil
	case "call":
		return client.Call(nil), nil
	case "company":
		return client.Company(nil), nil
	case "company_attached_contact":
		return client.CompanyAttachedContact(nil), nil
	case "company_attached_segment":
		return client.CompanyAttachedSegment(nil), nil
	case "company_list":
		return client.CompanyList(nil), nil
	case "company_scroll":
		return client.CompanyScroll(nil), nil
	case "contact":
		return client.Contact(nil), nil
	case "contact_attached_company":
		return client.ContactAttachedCompany(nil), nil
	case "contact_list":
		return client.ContactList(nil), nil
	case "contact_segment":
		return client.ContactSegment(nil), nil
	case "content":
		return client.Content(nil), nil
	case "content_import_source":
		return client.ContentImportSource(nil), nil
	case "content_search":
		return client.ContentSearch(nil), nil
	case "content_snippet":
		return client.ContentSnippet(nil), nil
	case "conversation":
		return client.Conversation(nil), nil
	case "conversation_attribute":
		return client.ConversationAttribute(nil), nil
	case "conversation_attribute_list":
		return client.ConversationAttributeList(nil), nil
	case "conversation_list":
		return client.ConversationList(nil), nil
	case "conversation_participant":
		return client.ConversationParticipant(nil), nil
	case "custom_object_instance":
		return client.CustomObjectInstance(nil), nil
	case "data":
		return client.Data(nil), nil
	case "data_attribute":
		return client.DataAttribute(nil), nil
	case "data_connector":
		return client.DataConnector(nil), nil
	case "data_connector_execution_result":
		return client.DataConnectorExecutionResult(nil), nil
	case "data_connector_execution_result_list":
		return client.DataConnectorExecutionResultList(nil), nil
	case "data_event":
		return client.DataEvent(nil), nil
	case "data_event_summary":
		return client.DataEventSummary(nil), nil
	case "data_export":
		return client.DataExport(nil), nil
	case "deleted":
		return client.Deleted(nil), nil
	case "deleted_article_object":
		return client.DeletedArticleObject(nil), nil
	case "deleted_company_object":
		return client.DeletedCompanyObject(nil), nil
	case "deleted_data_connector_object":
		return client.DeletedDataConnectorObject(nil), nil
	case "deleted_internal_article_object":
		return client.DeletedInternalArticleObject(nil), nil
	case "deleted_object":
		return client.DeletedObject(nil), nil
	case "email":
		return client.Email(nil), nil
	case "external_page":
		return client.ExternalPage(nil), nil
	case "fin_agent":
		return client.FinAgent(nil), nil
	case "handling_event":
		return client.HandlingEvent(nil), nil
	case "help_center":
		return client.HelpCenter(nil), nil
	case "internal_article":
		return client.InternalArticle(nil), nil
	case "internal_article_search":
		return client.InternalArticleSearch(nil), nil
	case "ip_allowlist":
		return client.IpAllowlist(nil), nil
	case "job":
		return client.Job(nil), nil
	case "macro":
		return client.Macro(nil), nil
	case "merge_history":
		return client.MergeHistory(nil), nil
	case "message":
		return client.Message(nil), nil
	case "news_item":
		return client.NewsItem(nil), nil
	case "newsfeed":
		return client.Newsfeed(nil), nil
	case "note":
		return client.Note(nil), nil
	case "office_hour":
		return client.OfficeHour(nil), nil
	case "office_hours_exception":
		return client.OfficeHoursException(nil), nil
	case "office_hours_schedule":
		return client.OfficeHoursSchedule(nil), nil
	case "paginated":
		return client.Paginated(nil), nil
	case "phone_switch":
		return client.PhoneSwitch(nil), nil
	case "reporting_data":
		return client.ReportingData(nil), nil
	case "reporting_data_export":
		return client.ReportingDataExport(nil), nil
	case "segment":
		return client.Segment(nil), nil
	case "side_conversation":
		return client.SideConversation(nil), nil
	case "subscription":
		return client.Subscription(nil), nil
	case "subscription_type":
		return client.SubscriptionType(nil), nil
	case "tag":
		return client.Tag(nil), nil
	case "team":
		return client.Team(nil), nil
	case "team_metric_list":
		return client.TeamMetricList(nil), nil
	case "ticket":
		return client.Ticket(nil), nil
	case "ticket_list":
		return client.TicketList(nil), nil
	case "ticket_reply":
		return client.TicketReply(nil), nil
	case "ticket_state":
		return client.TicketState(nil), nil
	case "ticket_type":
		return client.TicketType(nil), nil
	case "ticket_type_attribute":
		return client.TicketTypeAttribute(nil), nil
	case "visitor":
		return client.Visitor(nil), nil
	case "whatsapp_message_status":
		return client.WhatsappMessageStatus(nil), nil
	case "whatsapp_message_status_list":
		return client.WhatsappMessageStatusList(nil), nil
	case "workflow":
		return client.Workflow(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
