// Generated by sdkgen go-mcp target.
package main

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	"github.com/modelcontextprotocol/go-sdk/mcp"
	sdk "github.com/voxgig-sdk/intercom-sdk/go"
)

// Args is the common argument shape for both tools. `entity` selects
// the SDK entity to operate on; `query` is the optional reqmatch /
// reqdata map passed through to the SDK. For load, `query` should be
// `{"id": <value>}`. For list, omit `query` or pass an empty map.
type Args struct {
	Entity string         `json:"entity" jsonschema:"activity_log | activity_log_event_type | activity_log_list | admin | admin_with_app | ai_call | ai_content | article | article_search | article_version | article_version_list | audience | away_status_reason | banner | banner_dismiss | brand | call | company | company_attached_contact | company_attached_segment | company_list | company_scroll | contact | contact_attached_company | contact_list | contact_segment | content | content_import_source | content_search | content_snippet | conversation | conversation_attribute | conversation_attribute_list | conversation_list | conversation_participant | custom_object_instance | data | data_attribute | data_connector | data_connector_execution_result | data_connector_execution_result_list | data_event | data_event_summary | data_export | deleted | deleted_article_object | deleted_company_object | deleted_data_connector_object | deleted_internal_article_object | deleted_object | email | external_page | fin_agent | handling_event | help_center | internal_article | internal_article_search | ip_allowlist | job | macro | merge_history | message | news_item | newsfeed | note | office_hour | office_hours_exception | office_hours_schedule | paginated | phone_switch | reporting_data | reporting_data_export | segment | side_conversation | subscription | subscription_type | tag | team | team_metric_list | ticket | ticket_list | ticket_reply | ticket_state | ticket_type | ticket_type_attribute | visitor | whatsapp_message_status | whatsapp_message_status_list | workflow"`
	Query  map[string]any `json:"query,omitempty" jsonschema:"optional match map e.g. {\"id\":1} for load, omit for list"`
}

func registerTools(server *mcp.Server, client *sdk.IntercomSDK) {
	mcp.AddTool(server, &mcp.Tool{
		Name: "intercom_list",
		Description: "List records from Intercom. " +
			"Args: entity (one of the supported SDK entities), query (optional filter map). " +
			"Returns the first page of records as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "list", args)
	})

	mcp.AddTool(server, &mcp.Tool{
		Name: "intercom_load",
		Description: "Load a single record from Intercom. " +
			"Args: entity, query ({\"id\":N} required). Returns the record as JSON.",
	}, func(ctx context.Context, req *mcp.CallToolRequest, args Args) (*mcp.CallToolResult, any, error) {
		return runOp(client, "load", args)
	})
}

func runOp(client *sdk.IntercomSDK, op string, args Args) (*mcp.CallToolResult, any, error) {
	ent, err := entityFor(client, args.Entity)
	if err != nil {
		return toolError(err.Error())
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(args.Query, nil)
	case "load":
		result, err = ent.Load(args.Query, nil)
	default:
		return toolError(fmt.Sprintf("unknown op %q", op))
	}
	if err != nil {
		return toolError(err.Error())
	}

	// SDK returns *Entity wrappers; unwrap each via .Data() to get a
	// plain map[string]any (or []any of maps for list) suitable for
	// JSON marshalling.
	data := extractData(result)
	body, err := json.MarshalIndent(data, "", "  ")
	if err != nil {
		return toolError(fmt.Sprintf("marshal: %v", err))
	}
	return &mcp.CallToolResult{
		Content: []mcp.Content{
			&mcp.TextContent{Text: string(body)},
		},
	}, data, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.IntercomSDK, name string) (sdk.IntercomEntity, error) {
	switch strings.ToLower(name) {
	case "activity_log":
		return client.ActivityLog(nil), nil
	case "activity_log_event_type":
		return client.ActivityLogEventType(nil), nil
	case "activity_log_list":
		return client.ActivityLogList(nil), nil
	case "admin":
		return client.Admin(nil), nil
	case "admin_with_app":
		return client.AdminWithApp(nil), nil
	case "ai_call":
		return client.AiCall(nil), nil
	case "ai_content":
		return client.AiContent(nil), nil
	case "article":
		return client.Article(nil), nil
	case "article_search":
		return client.ArticleSearch(nil), nil
	case "article_version":
		return client.ArticleVersion(nil), nil
	case "article_version_list":
		return client.ArticleVersionList(nil), nil
	case "audience":
		return client.Audience(nil), nil
	case "away_status_reason":
		return client.AwayStatusReason(nil), nil
	case "banner":
		return client.Banner(nil), nil
	case "banner_dismiss":
		return client.BannerDismiss(nil), nil
	case "brand":
		return client.Brand(nil), nil
	case "call":
		return client.Call(nil), nil
	case "company":
		return client.Company(nil), nil
	case "company_attached_contact":
		return client.CompanyAttachedContact(nil), nil
	case "company_attached_segment":
		return client.CompanyAttachedSegment(nil), nil
	case "company_list":
		return client.CompanyList(nil), nil
	case "company_scroll":
		return client.CompanyScroll(nil), nil
	case "contact":
		return client.Contact(nil), nil
	case "contact_attached_company":
		return client.ContactAttachedCompany(nil), nil
	case "contact_list":
		return client.ContactList(nil), nil
	case "contact_segment":
		return client.ContactSegment(nil), nil
	case "content":
		return client.Content(nil), nil
	case "content_import_source":
		return client.ContentImportSource(nil), nil
	case "content_search":
		return client.ContentSearch(nil), nil
	case "content_snippet":
		return client.ContentSnippet(nil), nil
	case "conversation":
		return client.Conversation(nil), nil
	case "conversation_attribute":
		return client.ConversationAttribute(nil), nil
	case "conversation_attribute_list":
		return client.ConversationAttributeList(nil), nil
	case "conversation_list":
		return client.ConversationList(nil), nil
	case "conversation_participant":
		return client.ConversationParticipant(nil), nil
	case "custom_object_instance":
		return client.CustomObjectInstance(nil), nil
	case "data":
		return client.Data(nil), nil
	case "data_attribute":
		return client.DataAttribute(nil), nil
	case "data_connector":
		return client.DataConnector(nil), nil
	case "data_connector_execution_result":
		return client.DataConnectorExecutionResult(nil), nil
	case "data_connector_execution_result_list":
		return client.DataConnectorExecutionResultList(nil), nil
	case "data_event":
		return client.DataEvent(nil), nil
	case "data_event_summary":
		return client.DataEventSummary(nil), nil
	case "data_export":
		return client.DataExport(nil), nil
	case "deleted":
		return client.Deleted(nil), nil
	case "deleted_article_object":
		return client.DeletedArticleObject(nil), nil
	case "deleted_company_object":
		return client.DeletedCompanyObject(nil), nil
	case "deleted_data_connector_object":
		return client.DeletedDataConnectorObject(nil), nil
	case "deleted_internal_article_object":
		return client.DeletedInternalArticleObject(nil), nil
	case "deleted_object":
		return client.DeletedObject(nil), nil
	case "email":
		return client.Email(nil), nil
	case "external_page":
		return client.ExternalPage(nil), nil
	case "fin_agent":
		return client.FinAgent(nil), nil
	case "handling_event":
		return client.HandlingEvent(nil), nil
	case "help_center":
		return client.HelpCenter(nil), nil
	case "internal_article":
		return client.InternalArticle(nil), nil
	case "internal_article_search":
		return client.InternalArticleSearch(nil), nil
	case "ip_allowlist":
		return client.IpAllowlist(nil), nil
	case "job":
		return client.Job(nil), nil
	case "macro":
		return client.Macro(nil), nil
	case "merge_history":
		return client.MergeHistory(nil), nil
	case "message":
		return client.Message(nil), nil
	case "news_item":
		return client.NewsItem(nil), nil
	case "newsfeed":
		return client.Newsfeed(nil), nil
	case "note":
		return client.Note(nil), nil
	case "office_hour":
		return client.OfficeHour(nil), nil
	case "office_hours_exception":
		return client.OfficeHoursException(nil), nil
	case "office_hours_schedule":
		return client.OfficeHoursSchedule(nil), nil
	case "paginated":
		return client.Paginated(nil), nil
	case "phone_switch":
		return client.PhoneSwitch(nil), nil
	case "reporting_data":
		return client.ReportingData(nil), nil
	case "reporting_data_export":
		return client.ReportingDataExport(nil), nil
	case "segment":
		return client.Segment(nil), nil
	case "side_conversation":
		return client.SideConversation(nil), nil
	case "subscription":
		return client.Subscription(nil), nil
	case "subscription_type":
		return client.SubscriptionType(nil), nil
	case "tag":
		return client.Tag(nil), nil
	case "team":
		return client.Team(nil), nil
	case "team_metric_list":
		return client.TeamMetricList(nil), nil
	case "ticket":
		return client.Ticket(nil), nil
	case "ticket_list":
		return client.TicketList(nil), nil
	case "ticket_reply":
		return client.TicketReply(nil), nil
	case "ticket_state":
		return client.TicketState(nil), nil
	case "ticket_type":
		return client.TicketType(nil), nil
	case "ticket_type_attribute":
		return client.TicketTypeAttribute(nil), nil
	case "visitor":
		return client.Visitor(nil), nil
	case "whatsapp_message_status":
		return client.WhatsappMessageStatus(nil), nil
	case "whatsapp_message_status_list":
		return client.WhatsappMessageStatusList(nil), nil
	case "workflow":
		return client.Workflow(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with its underlying record (via .Data()).
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}

func toolError(msg string) (*mcp.CallToolResult, any, error) {
	return &mcp.CallToolResult{
		IsError: true,
		Content: []mcp.Content{
			&mcp.TextContent{Text: msg},
		},
	}, nil, nil
}
